### ISSUE TITLE
Great work, when the source codes can be released?

### ISSUE THREAD

**Issue by boxiangyun** [M3DV/LeFusion#1]

**Comment by duducheng** [comment]
Hi @boxiangyun ,

Thank you for your interest!

We plan to release the code once the paper is accepted by a visible venue.

Jiancheng

**Comment by QijingGJ** [comment]
hello, any news?

**Comment by duducheng** [comment]
thanks for your interest. We have a significant update these months, which will be released soon. We also plan to release the code in 2 weeks. Stay tuned!

JC

**Comment by kanydao** [comment]
Hi everyone, thank you all for your attention. We have already uploaded the basic code and added a link to our new version of the paper. This code repository will be continuously maintained and updated in the future.
@QijingGJ @boxiangyun 

Hantao
