### ISSUE TITLE
Inquiring About Code Release

### ISSUE THREAD

**Issue by TianmengHsu** [M3DV/LeFusion#2]
Hi, I really appreciate your work, and I'm curious about when it would be convenient for you to release the code. I believe it would be really beneficial for my understanding of the project. Thank you!

**Comment by duducheng** [comment]
Hi @TianmengHsu ,

thanks for your interest. We have a significant update these months, which will be released soon. We also plan to release the code in 2 weeks. Stay tuned!

JC

**Comment by kanydao** [comment]
Hi, @TianmengHsu We have already uploaded the basic code and added a link to our new version of the paper. This code repository will be continuously maintained and updated in the future. Thank you for your attention.

Hantao
