### ISSUE TITLE
Envrionment Issue

### ISSUE THREAD

**Issue by pedr0sorio** [M3DV/LeFusion#3]
Hey guys, 

Incredible work! I am really interested in trying to replicate this, but I am struggling with getting the environment right. It seems that some of the required lib versions are incompatible with the python version you specify. I noticed also you have a typo with your environment name. You create it as lefusion but activate it as medsam. I wonder if the readme needs some updating.

Thanks very much in advance!

Looking forward to trying the inference code soon

Best,
Pedro

**Comment by duducheng** [comment]
Thank you for interest and patience ;) Let me check with my colleagues @kanydao 

JC

**Comment by pedr0sorio** [comment]
Thanks very much for the fast response! That will do!
