### ISSUE TITLE
Inference doesn't work for batch_size > 1

### ISSUE THREAD

**Issue by pedr0sorio** [M3DV/LeFusion#5]
Dear LeFusion team,

Congrats again on the work and thanks again for being so supportive in answering my questions! As I mentioned in earlier issues, I am quite interested on using your model on my data, and I have successfully ran the inference on my machine. 

I've come across an issue which I thought best to communicate with you guys. In essence, the inference pipeline does not work for batches with size larger than 1. This can be easily replicated using by simply following the steps in the read me while hardcoding batch_size=2 in the following bit of your inference script:

```
dl = get_inference_dataloader(
        dataset_root_dir=conf.dataset_root_dir,
        test_txt_dir=conf.test_txt_dir,
        batch_size=2 # previously implicitly defined to 1
    )
```

The error trace is as follows:

```sampling...
length of dataset: 15
idx: 1
type_of_cond: 1
  0%|                                          | 0/300 [00:00<?, ?it/s]../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
  0%|                                          | 0/300 [00:00<?, ?it/s]
Error executing job with overrides: ['test_txt_dir=/home/pedroosorio/data/LIDC-IDRI/Pathological/test.txt', 'dataset_root_dir=/home/pedroosorio/data/LIDC-IDRI/Normal/Image/', 'target_img_path=/home/pedroosorio/data/LIDC-IDRI/gen/Image/', 'target_label_path=/home/pedroosorio/data/LIDC-IDRI/gen/Mask/', 'schedule_jump_params.jump_length=1', 'schedule_jump_params.jump_n_sample=1', 'batch_size=2']
Traceback (most recent call last):
  File "/home/pedroosorio/LeFusion/LeFusion_LIDC/test/inference.py", line 122, in main
    result = sample_fn(
  File "/opt/conda/envs/lefusion/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/pedroosorio/LeFusion/LeFusion_LIDC/ddpm/diffusion.py", line 701, in p_sample_loop_repaint
    for sample in self.p_sample_loop_repaint_progressive(
  File "/home/pedroosorio/LeFusion/LeFusion_LIDC/ddpm/diffusion.py", line 780, in p_sample_loop_repaint_progressive
    out = self.p_sample_repaint(image_after_step, torch.full((b,), t_last_t, device=device, dtype=torch.long), cond_scale=cond_scale,
  File "/home/pedroosorio/LeFusion/LeFusion_LIDC/ddpm/diffusion.py", line 736, in p_sample_repaint
    gt_weight = torch.sqrt(alpha_cumprod)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I understand this an early release so more complete versions of this codebase could be in your horizon, although I would note that it would be cool to have this working for larger batches. This would ideally include also the possibility of specifying different histogram vectors for each element in the batch, which is something I am not sure is already in place.

I am looking into how to address this, but the solution might be more immediate for you guys.

Thanks in advance!

Best,
Pedro

**Comment by pedr0sorio** [comment]
So it seems like this line is the culprit:

https://github.com/M3DV/LeFusion/blob/a873c18223d3a2e06be58253693f597978647c29/LeFusion_LIDC/ddpm/diffusion.py#L776

I just changed it to `t_last_t = t_last` and inference now works. However, I am not very familiar with the RePaint implementation so I am not sure this is an adequate solution. What is the reason behind multiplying the previous time step by the batch size?

**Comment by kanydao** [comment]
Hi @pedr0sorio ! 

Thank you for your valuable feedback and attention. From an algorithmic perspective, Lefusion indeed supports multi-batch-size inference and allows for specifying unique histogram vectors for each batch element. In the initial development phase, we set the batch size to 1 to streamline testing, visualization, and rapid iteration of the algorithm. We are now restructuring the code to fully enable multi-batch-size inference capabilities, so please stay tuned for upcoming versions.

For the code t_last_t = t_last * shape[0], I believe the primary intention was to ensure that t_last_t and t_last have consistent data formats. When the batch size is set to 1, the values of t_last_t and t_last are indeed the same. However, during additional testing, I observed that both t_last_t and t_last are of the int type, leading me to conclude that your approach is correct. Therefore, using t_last_t = t_last should work directly for handling multiple batch sizes.

We conducted the relevant tests and found everything to be working as expected. The corresponding code will be updated shortly. If you have any further questions, please feel free to contact me.

Best,
Hantao
