### ISSUE TITLE
LeFusion 3D Slicer plugin

### ISSUE THREAD

**Issue by pedr0sorio** [M3DV/LeFusion#6]
Hey LeFusion Team,

It is me again! I put together a small 3D slicer extension that uses your inpainting model on the backend. This is useful for some applications I am interested in and I think it is what is lacking to get your model closer to the radiologists. That could be useful for as an extra evaluation. Have a look: [lefusion-slicer](https://github.com/pedr0sorio/lefusion-slicer)

Please feel free to use it or to contribute to it :)

**Comment by duducheng** [comment]
Wow, thank you so much for your incredible contribution! This is extremely useful.

We'd be delighted to showcase your masterpiece and feature it in our README!

JC

**Comment by pedr0sorio** [comment]
My pleasure! I'd be happy to have it featured on your README!
